from gunicorn.workers.base_async import AsyncWorker as AsyncWorker

def patch_sendfile() -> None: ...

class EventletWorker(AsyncWorker):
    def patch(self) -> None: ...
    def is_already_handled(self, respiter): ...
    def init_process(self) -> None: ...
    def handle_quit(self, sig, frame) -> None: ...
    def handle_usr1(self, sig, frame) -> None: ...
    def timeout_ctx(self): ...
    def handle(self, listener, client, addr) -> None: ...
    def run(self) -> None: ...
